if isServer() then
    return
end

-- ---------------------------------------------------------------------------
-- Project Viewpoint (workshop 3809306528) draws the world in 3D from tile
-- flags, and colours walls and floors from tables keyed by vanilla sprite
-- name. Ours are in none of them, so the black shells came out as grey slabs
-- seamed at every tile and the ground inside a shell as sky blue.
--
-- A Viewpoint model pack replaces that geometry sprite by sprite. Ours is
-- generated by scripts/viewpointpack.pl into media/viewpoint/, and nothing in
-- it is drawn by anything but Viewpoint, so the iso view is unaffected.
--
-- A soft hook: Viewpoint.ModelPacks only exists while Viewpoint's Java is
-- loaded, which needs ZombieBuddy and the player's approval. Registered on
-- boot and again on game start, as the Voxel Studio pack does, because the
-- Java side may not be up when this file first runs. A repeat is harmless
-- either way: ModelPacks.register remembers each (mod, manifest) pair and
-- answers a second call with whether the first one loaded, and it answers
-- false, printing why, for a manifest it cannot find.
-- ---------------------------------------------------------------------------

local MANIFEST = "media/viewpoint/phuninteriors.properties"

-- The test build ships under its own id; ModelPacks resolves the manifest
-- against the folder of the mod it is named for.
local function ourModId()
    local mods = getActivatedMods()
    if mods:contains("phuninteriorstest") then
        return "phuninteriorstest"
    end
    return "phuninteriors"
end

local registered = false

local function register()
    if registered or not Viewpoint or not Viewpoint.ModelPacks then
        return
    end
    local ok, result = pcall(Viewpoint.ModelPacks.register, ourModId(), MANIFEST)
    if not ok then
        print("[PhunInteriors] Viewpoint model pack: " .. tostring(result))
        return
    end
    if result then
        registered = true
        print("[PhunInteriors] registered the Viewpoint model pack")
    end
end

Events.OnGameBoot.Add(register)
Events.OnGameStart.Add(register)
register()
