#!/usr/bin/perl
# Build the Project Viewpoint model pack for our own tilesheet, into
# Contents/mods/PhunInteriors/common/media/viewpoint/. Run from the repo root.
#
#   perl scripts/viewpointpack.pl            # shell walls 3 levels tall
#   perl scripts/viewpointpack.pl 1          # or as many as you like
#
# Viewpoint (workshop 3809306528) builds walls and floors from tile flags and
# colours them from tables keyed by VANILLA sprite name, none of which are
# ours. So the black shells came out as grey slabs with a seam at every tile,
# and the ground inside a shell came out sky blue. A model pack binds a sprite
# to an OBJ, and that replaces Viewpoint's own geometry for it outright: the
# bind is tested first for each object in WorldMesher.square, ahead of both
# FloorGather.capture and WallMesher.wall.
#
# Model space, read off the Voxel Studio pack (3810302175): origin at the
# CENTRE of the square, x east, y SOUTH (map orientation, so -y is the north
# edge), z up, one level about 2.45. vanilla's SE post,
# walls_exterior_wooden_01_3, sits at x -0.49, y -0.46, which is the NW
# corner where PZ draws it. Bind lines are model,degrees,x,y,z,scale.
#
# The reader takes a texture from map_Kd and nothing else -- a bare Kd colour
# is ignored -- hence the 4x4 png. Every face is written in both windings
# because nothing here settles which way Viewpoint culls.
#
# Height is a 3D-only choice. A z=1 course was tried twice on the map and
# banded in the iso view (CLAUDE.md, Known gaps #1); a model is drawn only by
# Viewpoint, so the iso view is untouched however tall this is.
use strict; use warnings;
use Compress::Zlib qw(compress crc32);

# --debug paints the floor red and the walls green, to tell which surface a
# stray colour in game belongs to and whether our texture is reaching it.
my $debug = grep { $_ eq "--debug" } @ARGV;
@ARGV = grep { $_ ne "--debug" } @ARGV;

my $levels = shift // 3;
die "viewpointpack: levels must be a positive number\n" unless $levels =~ /^\d+(\.\d+)?$/ and $levels > 0;
my $LEVEL = 2.45;
my $H     = $levels * $LEVEL;
my $T     = 0.12;           # wall thickness, centred on the tile edge
my $LAP   = $T / 2;         # each panel runs this far past its tile, closing the seams
my $SLAB  = 0.04;           # floor thickness, below the floor line
my $LIFT  = 0.004;          # how far the lid sits above the floor line
my $SKIN  = 0.008;          # and how thick it is
my $SHADE = 10;             # 0-255 grey; pure black reads as a hole in lit scenes
my @FLOOR = $debug ? (220, 0, 0) : ($SHADE) x 3;
my @WALL  = $debug ? (0, 220, 0) : ($SHADE) x 3;

my $out = "Contents/mods/PhunInteriors/common/media/viewpoint";
-d "Contents/mods/PhunInteriors" or die "viewpointpack: run from the repo root\n";
mkdir $out unless -d $out;

# --- geometry --------------------------------------------------------------

# One axis-aligned box as OBJ text, both windings per face.
sub box {
    my ($x0, $x1, $y0, $y1, $z0, $z1) = @_;
    my (@v, @f);
    my @faces = (
        # four corners, counter-clockwise seen from outside, then the normal
        [[$x0,$y0,$z1],[$x1,$y0,$z1],[$x1,$y1,$z1],[$x0,$y1,$z1], [0,0,1]],
        [[$x0,$y1,$z0],[$x1,$y1,$z0],[$x1,$y0,$z0],[$x0,$y0,$z0], [0,0,-1]],
        [[$x0,$y0,$z0],[$x1,$y0,$z0],[$x1,$y0,$z1],[$x0,$y0,$z1], [0,-1,0]],
        [[$x1,$y1,$z0],[$x0,$y1,$z0],[$x0,$y1,$z1],[$x1,$y1,$z1], [0,1,0]],
        [[$x0,$y1,$z0],[$x0,$y0,$z0],[$x0,$y0,$z1],[$x0,$y1,$z1], [-1,0,0]],
        [[$x1,$y0,$z0],[$x1,$y1,$z0],[$x1,$y1,$z1],[$x1,$y0,$z1], [1,0,0]],
    );
    return \@faces;
}

sub obj {
    my ($file, $mtl, @boxes) = @_;
    my ($vs, $ns, $fs) = ("", "", "");
    my ($nv, $nn) = (0, 0);
    for my $b (@boxes) {
        for my $face (@$b) {
            my @c = @$face[0..3];
            my $n = $face->[4];
            $vs .= sprintf("v %.4f %.4f %.4f\n", @$_) for @c;
            $ns .= sprintf("vn %d %d %d\n", @$n);
            $ns .= sprintf("vn %d %d %d\n", map { -$_ } @$n);
            my ($a, $b2, $c2, $d) = map { $nv + $_ } 1..4;
            my ($out_n, $in_n) = ($nn + 1, $nn + 2);
            # Triangles, as every model in the Voxel Studio pack is: nothing
            # says ObjReader splits a quad.
            $fs .= "f $a/1/$out_n $b2/2/$out_n $c2/3/$out_n\n";
            $fs .= "f $a/1/$out_n $c2/3/$out_n $d/4/$out_n\n";
            $fs .= "f $c2/3/$in_n $b2/2/$in_n $a/1/$in_n\n";
            $fs .= "f $d/4/$in_n $c2/3/$in_n $a/1/$in_n\n";
            $nv += 4;
            $nn += 2;
        }
    }
    open my $fh, ">", "$out/$file" or die "viewpointpack: $file: $!\n";
    print $fh "# generated by scripts/viewpointpack.pl -- do not edit\n";
    print $fh "mtllib $mtl.mtl\nusemtl m\n";
    print $fh $vs;
    print $fh "vt 0.125 0.125\nvt 0.875 0.125\nvt 0.875 0.875\nvt 0.125 0.875\n";
    print $fh $ns, $fs;
    close $fh;
}

my $e = 0.5;
# West wall: along the west edge, the full tile north to south plus the lap.
my $west  = box(-$e - $T/2, -$e + $T/2, -$e - $LAP, $e + $LAP, 0, $H);
# North wall: along the north edge.
my $north = box(-$e - $LAP, $e + $LAP, -$e - $T/2, -$e + $T/2, 0, $H);
# SE post: PZ draws it at the north-west corner of its own square.
my $post  = box(-$e - $T/2, -$e + $T/2, -$e - $T/2, -$e + $T/2, 0, $H);
# Floor: a slab whose top is the floor line, lapped so tiles meet.
my $floor = box(-$e - 0.002, $e + 0.002, -$e - 0.002, $e + 0.002, -$SLAB, 0);
# Lid: the same tile, lifted just OFF the floor line. Every room is capped at
# z=1 by phuninteriors_01_1 painted over the room's own ceiling sprite, and
# Viewpoint draws both. As a floor slab the lid hung below the floor line,
# under that ceiling, so it was what a tenant saw looking up: a black
# ceiling. Lifted, the room's own ceiling is nearer the tenant and hides it,
# while from above the lid still covers the ceiling as the iso view does.
my $lid   = box(-$e - 0.002, $e + 0.002, -$e - 0.002, $e + 0.002, $LIFT, $LIFT + $SKIN);

# Every wall model carries a floor slab too. A square that holds a shell wall
# holds NO ground tile -- all 2331 of them in 87,46, against 62455 squares of
# ground and no square with both -- because the iso view never shows the
# floor under a wall sprite. In 3D nothing was drawn there, and the strip
# along the foot of every shell wall was a hole into the sky below. It is the
# LIFTED slab, not the floor one: the same sprites ring every lid at z=1, and
# the ring's north and west pieces stand over the room's own top row and
# column, so a slab hung below the floor line there would black out that
# strip of ceiling exactly as the lid used to. At z=0 nobody stands in a wall
# square, so a centimetre of lift there is invisible.
obj("wall_w.obj",  "wall",  $west, $lid);
obj("wall_n.obj",  "wall",  $north, $lid);
obj("wall_nw.obj", "wall",  $west, $north, $lid);
obj("post_se.obj", "wall",  $post, $lid);
obj("floor.obj",   "floor", $floor);
obj("lid.obj",     "floor", $lid);

# --- material --------------------------------------------------------------

# One flat colour per material, so the floor and the walls can be told apart
# in game with --debug.
sub chunk {
    my ($type, $data) = @_;
    return pack("N", length $data) . $type . $data . pack("N", crc32($type . $data));
}
sub material {
    my ($name, @rgb) = @_;
    open my $m, ">", "$out/$name.mtl" or die "viewpointpack: $name.mtl: $!\n";
    print $m "newmtl m\nKd 1 1 1\nd 1\nmap_Kd $name.png\n";
    close $m;
    my $w = 4;
    my $raw = join "", map { "\0" . (pack("C3", @rgb) x $w) } 1..$w;
    my $png = "\x89PNG\r\n\x1a\n"
            . chunk("IHDR", pack("NNCCCCC", $w, $w, 8, 2, 0, 0, 0))
            . chunk("IDAT", compress($raw))
            . chunk("IEND", "");
    open my $p, ">:raw", "$out/$name.png" or die "viewpointpack: $name.png: $!\n";
    print $p $png;
    close $p;
}
material("wall",  @WALL);
material("floor", @FLOOR);
unlink "$out/black.mtl", "$out/black.png";

# --- manifest --------------------------------------------------------------

my %bind = (
    "phuninteriors_01_0"  => "pi-floor",    # the ground under the whole block
    "phuninteriors_01_1"  => "pi-lid",      # the black lid over every room
    "phuninteriors_01_8"  => "pi-wall-w",   # WallW
    "phuninteriors_01_9"  => "pi-wall-n",   # WallN
    "phuninteriors_01_10" => "pi-wall-nw",  # WallNW
    "phuninteriors_01_11" => "pi-post-se",  # WallSE
);
open my $mf, ">", "$out/phuninteriors.properties" or die "viewpointpack: manifest: $!\n";
print $mf "# generated by scripts/viewpointpack.pl -- do not edit\n";
print $mf "id=phuninteriors\nname=PhunInteriors shells\nversion=1\n";
print $mf "model.pi-floor=floor.obj\n";
print $mf "model.pi-lid=lid.obj\n";
print $mf "model.pi-wall-w=wall_w.obj\n";
print $mf "model.pi-wall-n=wall_n.obj\n";
print $mf "model.pi-wall-nw=wall_nw.obj\n";
print $mf "model.pi-post-se=post_se.obj\n";
print $mf "bind.$_=$bind{$_},0,0,0,0,1\n" for sort keys %bind;
close $mf;

printf "viewpointpack: walls %s level%s (%.2f high)%s into %s\n", $levels, $levels == 1 ? "" : "s", $H,
    $debug ? ", DEBUG colours" : "", $out;
